name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true         

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install --server=https://luarocks.org/dev luaunit
          sudo luarocks install --server=https://luarocks.org/dev plenary.nvim

      - name: Run tests
        run: |
          nvim --headless -c "PlenaryBustedDirectory tests/ {minimal_init = './tests/minimal_init.vim'}"
